Update docs for turbot_resource
turbot/terraform-provider-turbot pull request #74
Opened 2020-07-23 11:48 UTC by RupeshPatil20

2020-07-23 15:25 UTC, kaidaguerre requested changes

2020-07-23 15:25 UTC, kaidaguerre commented on website/docs/r/resource.html.markdown
> +- `data` - (Required) JSON representation of the details of the resource, managed on merge basis. When parsed, it must be valid for the `type` schema.
`data` - (Optional) JSON representation of resource properties to be managed by Terraform. These must be valid for the resource`type` schema. NOTE: If additional properties are set on the resource by other means, they are ignored by Terraform. 
`metadata` - (Optional) JSON representation of resource metadata properties to be managed by Terraform. NOTE: If additional metadata properties are set on the resource by other means, they are ignored by Terraform. 
`full_data` - (Optional) JSON representation of all resource properties to be set on the resource. These must be valid for the resource`type` schema. NOTE: If additional properties are set on the resource by other means, they are removed. 
`full_metadata` - (Optional) JSON representation of all resource metadata properties to be set on the resource. NOTE: If additional metadata properties are set on the resource by other means, they are removed.

2020-07-23 15:25 UTC, kaidaguerre commented on website/docs/r/resource.html.markdown
>  - `parent` - (Required) The `id` or `aka` of the level at which the Turbot resource will be created.
- `parent` - (Required) The identifier of the parent resource under which this resource will be created.

2020-07-23 15:25 UTC, kaidaguerre commented on website/docs/r/resource.html.markdown
> +  "foo": "bar",
have realistic properties in the example

2020-07-31 16:51 UTC, kaidaguerre requested changes

2020-07-31 16:51 UTC, kaidaguerre commented on website/docs/r/resource.html.markdown
> +  "type": "aws",
if it's full data  you should probably include account id

2020-07-31 16:51 UTC, kaidaguerre commented on website/docs/r/resource.html.markdown
> +**NOTE**: You must not specify `data` and `full_data` OR `metadata` and `full_metadata` arguments together.
NOTE: only one of `data` and `full_data` may be specified. Likewise,  only one of `metadata ` and `full_metadata ` may be set.

2020-08-19 14:49 UTC, kaidaguerre requested changes

2020-08-19 14:49 UTC, kaidaguerre commented on website/docs/r/resource.html.markdown
> +- `full_data` - (Optional) JSON representation of all resource properties to be set on the resource. These must be valid for the type schema. NOTE: If additional properties are set on the resource by
The data must be valid for the resource type schema

2020-08-19 14:49 UTC, kaidaguerre commented on website/docs/r/resource.html.markdown
> +- `data` - (Optional) JSON representation of resource properties to be managed by Terraform. These must be valid for the type schema. NOTE: If additional properties are set on the resource by other m
JSON only or yaml as well?

2020-08-19 18:10 UTC, RupeshPatil20 commented on website/docs/r/resource.html.markdown
> +  "type": "aws",
added Id in full_data

2020-08-20 08:08 UTC, RupeshPatil20 commented on website/docs/r/resource.html.markdown
> +- `data` - (Optional) JSON representation of resource properties to be managed by Terraform. These must be valid for the type schema. NOTE: If additional properties are set on the resource by other m
Strictly JSON

2020-08-27 08:27 UTC, merged